version: "3"
services:
  handson-ml:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - username=devel
        - userid=1000
    container_name: handson-mlpractice
    image: handson-mlpractice
    logging:
      driver: json-file
      options:
        max-size: 50m
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/home/devel/handson-mlpractice
    command: /opt/conda/bin/jupyter notebook --ip='*' --port=8888 --no-browser
